#!/bin/bash

clear

function reset(){
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;31m wait for me.. \033[1;36m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;37m* "
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;37m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;31m wait for me.. \033[1;36m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m YES!\033[0m"
    tput cnorm
}
res1() {
    systemctl daemon-reload
}
res2() {
    systemctl restart nginx
}
res3() {
    systemctl restart xray
}
res4() {
    systemctl restart rc-local
}
res5() {
    systemctl restart client
}
res6() {
    systemctl restart server
}
res7() {
    systemctl restart dropbear
}
res8() {
    systemctl restart ws
}
res9() {
    systemctl restart openvpn
}
res10() {
    systemctl restart cron
}
res11() {
    systemctl restart haproxy
}
res12() {
    systemctl restart netfilter-persistent
}
res13() {
    systemctl restart squid
}
res14() {
    systemctl restart badvpn1
    systemctl restart badvpn2
    systemctl restart badvpn3
}
netfilter-persistent
clear
echo -e "\033[44;1m                RESTARTING FIX SERVICE                   \e[0m"
echo -e ""
echo -e "  \033[1;91m DAEMON-RELOAD      \033[0m"
fun_bar 'res1'
echo -e "  \033[1;91m STATUSES NGINX     \033[0m"
fun_bar 'res2'
echo -e "  \033[1;91m STATUSES X-RAY     \033[0m"
fun_bar 'res3'
echo -e "  \033[1;91m STATUSES RC-ROCAL  \033[0m"
fun_bar 'res4'
echo -e "  \033[1;91m STATUSES DROPBEAR  \033[0m"
fun_bar 'res7'
echo -e "  \033[1;91m STATUSES WEBSOCKET \033[0m"
fun_bar 'res8'
echo -e "  \033[1;91m STATUSES OPENVPN   \033[0m"
 fun_bar 'res9'
echo -e "  \033[1;91m STATUSES CRONS-JOB \033[0m"
fun_bar 'res10'
 echo -e " \033[1;91m STATUSES HAPROXY   \033[0m"
fun_bar 'res11'
echo -e "  \033[1;91m STATUSES BADVPN    \033[0m"
fun_bar 'res14'
echo -e ""
}

reset


exec bash