#!/bin/bash
clear
echo -e "\e[97;1m =============================================\e[0m"
echo -e "\e[97;1m         RENEW SSH/OPENVPN ACCOUNT            \e[0m"
echo -e "\e[97;1m =============================================\e[0m"
echo -e "\e[97;1m =============================================\e[0m"
echo -e "\e[0;37m USERNAME          EXP DATE          STATUS"
echo -e "\e[97;1m =============================================\e[0m"
# Deklarasi array untuk menyimpan username
declare -a user_list

# Tampilkan username member dengan indeks
index=1
while read expired; do
    AKUN="$(echo $expired | cut -d: -f1)"
    ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
    exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
    status="$(passwd -S $AKUN | awk '{print $2}' )"
    if [[ $ID -ge 1000 ]]; then
        if [[ "$status" = "L" ]]; then
            printf "%-3s %-17s %2s %-17s %2s \n" "$index)" "$AKUN" "$exp     " "LOCKED"
        else
            printf "%-3s %-17s %2s %-17s %2s \n" "$index)" "$AKUN" "$exp     " "UNLOCKED"
        fi
        user_list[$index]=$AKUN
        ((index++))
    fi
done < /etc/passwd

echo -e "\e[97;1m =============================================\e[0m"
echo -e ""
# Pilih user berdasarkan nomor
read -p " just Input number:  " number
User=${user_list[$number]}

# Cek apakah username valid
if [[ -n "$User" ]]; then
    read -p " Day Extend   : " Days
    read -p " Limit Devic  : " IP_LIMIT
    
    echo "${IP_LIMIT}" >> /etc/lunatic/ssh/$User
    Today=$(date +%s)
    Days_Detailed=$((Days * 86400))
    Expire_On=$((Today + Days_Detailed))
    Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
    Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
    passwd -u $User
    usermod -e $Expiration $User
    echo -e "Your password is reset"
    clear

    # Sukses renew
echo -e "\e[97;1m =========================================\e[0m"    
    echo -e "\e[92;1m Successfully SSH renewed             "
    echo -e "\e[37;1m Username   : $User"
    echo -e "\e[37;1m Days Added : $Days Days"
    echo -e "\e[37;1m Expires on : $Expiration_Display     \e[0m"
echo -e "\e[97;1m =========================================\e[0m"
else
    clear
    # Gagal renew, nomor tidak valid
    echo -e "\e[97;1m =============================================\e[0m"
    echo -e "\e[31;1m    Invalid selection. $User not found.       \e[0m"
    echo -e "\e[97;1m =============================================\e[0m"
    echo ""
    exit 1
fi


exec bash