#!/bin/bash
clear
# Ambil data nama dari config.json
users=$(grep -E "^#! " "/etc/xray/config.json" | sed -E 's/^#! ([^ ]+).*/\1/' | awk '!seen[$0]++')

# Tampilkan username
echo -e "\e[97;1m =======[ X-RAY TROJAN RENEW ]========= \e[0m"

i=1
for user in $users; do
    echo "$i) $user"
    ((i++))
done

echo -e "\e[97;1m ====================================== \e[0m"
echo ""
read -p " Just input Number: " number
USERNAME=$(echo "$users" | sed -n "${number}p")
if [ -z "$USERNAME" ]; then    
		clear
echo -e "\e[97;1m ====================================== \e[0m"
echo -e "\e[0;31m    Sorry                               \e[0m "
echo -e "\033[38;5;226m    Maaf Nama tidak ada atau -    \e[0m"
echo -e "\033[38;5;226m    Anda salah Memasukan nama     \e[0m"
echo -e "\e[97;1m ====================================== \e[0m"

    exit 1
else
# input New Data
clear
echo -e "\e[97;1m ====================================== \e[0m"
echo -e "\033[38;5;226m Input New Data from User\e[32;1m $USERNAME\e[0m"
echo -e "\e[97;1m ====================================== \e[0m"
echo -e ""
echo
read -p " Expired (day)    : " LIMIT_DAYS
echo
read -p " Limit User (GB)  : " LIMIT_QUOTA
echo
read -p " Limit User (IP)  : " LIMIT_DEVIC
echo

clear

exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
mkdir -p /etc/lunatic/trojan/ip

# Save Limit IP to user
echo ${LIMIT_DEVIC} >> /etc/lunatic/trojan/ip/${user}
if [ ! -e /etc/lunatic/trojan ]; then
  mkdir -p /etc/lunatic/trojan
fi

# cek quota apakah nol ?
if [ -z ${LIMIT_QUOTA} ]; then
  LIMIT_QUOTA="0"
fi

# Calculate Quota GB to bytes formatted
FORMATTED_QUOTA=$(echo "${LIMIT_QUOTA}" | sed 's/[^0-9]*//g')
USAGE_QUOTA=$((${FORMATTED_QUOTA} * 1024 * 1024 * 1024))

# Save New Quota to user
if [[ ${FORMATTED_QUOTA} != "0" ]]; then
  echo "${USAGE_QUOTA}" >/etc/lunatic/trojan/usage/${user}
fi
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    DAYS_LEFT=$(( (d1 - d2) / 86400 ))
    exp3=$(($DAYS_LEFT + $LIMIT_DAYS))
    EXPIRY_DATE=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "/#! $user/c\#! $user $EXPIRY_DATE" /etc/xray/config.json
    sed -i "/### $user/c\### $user $EXPIRY_DATE" /etc/lunatic/trojan/.trojan.db
    systemctl restart xray > /dev/null 2>&1
    clear
    echo -e "\e[97;1m ====================================== \e[0m"
    echo -e "\e[92;1m Succesfully \e[0m "
    echo -e "\e[97;1m Client Name    :\033[38;5;226m $USERNAME                    \e[0m"
    echo -e "\e[97;1m Expired On     :\033[38;5;226m $EXPIRY_DATE/$DAYS_LEFT days \e[0m"
    echo -e "\e[97;1m Quota Limit    :\033[38;5;226m $LIMIT_QUOTA GB              \e[0m"
    echo -e "\e[97;1m Devic Limit    :\033[38;5;226m $LIMIT_DEVIC IP              \e[0m"
    echo -e "\e[97;1m ====================================== \e[0m"
    echo -e ""
    fi
    
    
    exec bash