#!/bin/bash
clear
# Baca nama pengguna dari config.json, pisahkan username dan tanggal expired, lalu hilangkan duplikat
users=$(grep -E "^#! " "/etc/xray/config.json" | sed -E 's/^#! ([^ ]+).*/\1/' | awk '!seen[$0]++')

# Tampilkan nama pengguna dengan nomor urut
echo -e "\e[97;1m ====================================== \e[0m"

i=1
for user in $users; do
    echo "$i) $user"
    ((i++))
done

echo -e "\e[97;1m ====================================== \e[0m"

echo ""
# Minta pengguna memilih nomor
read -p " Just input Number: " number

# Dapatkan username berdasarkan nomor yang dipilih
selected_user=$(echo "$users" | sed -n "${number}p")

if [ -z "$selected_user" ]; then
    echo -e "\e[31;1m number is missing or incorrect\e[0m"
    exit 1
fi

# Tampilkan Detail Akun User
clear
cat /etc/lunatic/trojan/detail/$selected_user.txt



exec bash